---

- name: Create qBittorrent directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ qbittorrent_config_directory }}"

- name: Set Docker container parameters
  set_fact:
    qbittorrent_container_parameters:
      name: "{{ qbittorrent_name }}"
      image: "{{ qbittorrent_image }}"
      state: started
      published_ports: "{{ qbittorrent_ports }}"
      volumes:
        - "{{ qbittorrent_config_directory }}:/config"
        - "{{ qbittorrent_download_directory }}:/downloads"
      env: "{{ qbittorrent_environment_variables }}"

- name: Create qBittorrent container
  docker_container: "{{ qbittorrent_container_parameters | combine(qbittorrent_docker_additional_options) }}"
  register: qbittorrent_container

- name: Wait for qBittorrent start
  wait_for:
    port: "{{ qbittorrent_webui_port }}"
    host: "{{ qbittorrent_container.container.NetworkSettings.IPAddress }}"
    timeout: 60

- name: Configure qBittorrent
  ini_file:
    path: "{{ qbittorrent_config_directory }}/qBittorrent/qBittorrent.conf"
    section: "{{ item.key.split('.')[0] }}"
    option: "{{ item.key.split('.')[1] }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
  with_items: "{{ qbittorent_config | dict2items }}"
  notify: Restart qBittorrent
